---
title: "Coding More"

```{r warning=FALSE, message=FALSE}
library(Lahman)
library(sqldf)
library(ggplot2)
```

#extracting the data-----------------------------------

```{r}
query<-"SELECT playerID, sum(HR) AS career_HR, sum(SO) AS career_SO
FROM Batting
GROUP BY playerID
HAVING sum(HR)>=400"

result<-sqldf(query)
```

# visualizing the data-------------------------------------

```{r}
ggplot()+
  geom_point(data=result,aes(x=career_SO,y=career_HR),size=3,color="blue")+
  ggtitle("Career Strikeouts VS Homeruns for great Hitters")+
  xlab("Career Strikeouts")+ 
  ylab("Career Homeruns")
```

# extracting the data------------------------------------------

```{r}
query<-"SELECT weight
FROM Master"

result<-sqldf(query)
```

#visualization-------------------------------------------------

```{r}
ggplot()+
  geom_histogram(data=result,aes(x=weight),color="blue",fill="white",size=1,bins=100)+
ggtitle("Baseball Player Wheight Distribution")

```


#extracting the data---------------------------------------

```{r}
query<-"SELECT yearID,HR
FROM Batting
WHERE playerID='ruthba01'"

result<-sqldf(query)
```

#visualizing the data---------------------------------------

```{r}
ggplot()+
  geom_line(data=result,aes(x=yearID, y=HR))+
  geom_point(data=result,aes(x=yearID, y=HR))+
  ggtitle("Ruth's Homerun Totals Through the Years")+
  xlab("year")+
  ylab("homeruns")
```



